name: Build agents

on:
  push:
    branches:
     - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: node ./build-web-agent.js
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builded-instructions
          path: |
            build
